-- ============================================================
-- Risk, Fraud & Regulatory Intelligence Copilot
-- Step 4: Risk Detection Views & Evidence Generation
-- ============================================================

USE SCHEMA RISK_COPILOT.PUBLIC;

-- Structuring detection: clusters of sub-$10k cash deposits
CREATE OR REPLACE VIEW V_STRUCTURING_ALERTS AS
SELECT 
    t.CUSTOMER_ID,
    c.FULL_NAME,
    DATE(t.TXN_DATE) AS TXN_DAY,
    COUNT(*) AS CASH_DEPOSIT_COUNT,
    SUM(t.AMOUNT) AS TOTAL_AMOUNT,
    AVG(t.AMOUNT) AS AVG_DEPOSIT,
    MAX(t.AMOUNT) AS MAX_DEPOSIT,
    LISTAGG(t.TXN_ID, ', ') WITHIN GROUP (ORDER BY t.TXN_DATE) AS RELATED_TXNS
FROM TRANSACTIONS t
JOIN CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
WHERE t.TXN_TYPE = 'CASH_DEPOSIT'
  AND t.AMOUNT BETWEEN 8000 AND 9999
GROUP BY t.CUSTOMER_ID, c.FULL_NAME, DATE(t.TXN_DATE)
HAVING COUNT(*) >= 2;

-- Velocity anomaly: daily txn count >= 3x average
CREATE OR REPLACE VIEW V_VELOCITY_ANOMALIES AS
WITH daily_counts AS (
    SELECT CUSTOMER_ID, DATE(TXN_DATE) AS TXN_DAY, COUNT(*) AS DAILY_TXN_COUNT
    FROM TRANSACTIONS GROUP BY CUSTOMER_ID, DATE(TXN_DATE)
),
avg_counts AS (
    SELECT CUSTOMER_ID, AVG(DAILY_TXN_COUNT) AS AVG_DAILY_COUNT
    FROM daily_counts GROUP BY CUSTOMER_ID
)
SELECT d.CUSTOMER_ID, c.FULL_NAME, d.TXN_DAY, d.DAILY_TXN_COUNT,
    ROUND(a.AVG_DAILY_COUNT, 1) AS AVG_DAILY_COUNT,
    ROUND(d.DAILY_TXN_COUNT / NULLIF(a.AVG_DAILY_COUNT, 0), 1) AS VELOCITY_MULTIPLIER
FROM daily_counts d
JOIN avg_counts a ON d.CUSTOMER_ID = a.CUSTOMER_ID
JOIN CUSTOMERS c ON d.CUSTOMER_ID = c.CUSTOMER_ID
WHERE d.DAILY_TXN_COUNT >= 3 * a.AVG_DAILY_COUNT AND d.DAILY_TXN_COUNT >= 3;

-- High-risk jurisdiction transactions
CREATE OR REPLACE VIEW V_HIGH_RISK_JURISDICTIONS AS
SELECT t.TXN_ID, t.CUSTOMER_ID, c.FULL_NAME, t.TXN_DATE, t.TXN_TYPE,
    t.AMOUNT, t.CURRENCY, t.COUNTERPARTY, t.COUNTERPARTY_COUNTRY,
    c.COUNTRY AS CUSTOMER_COUNTRY, c.JURISDICTION_RISK
FROM TRANSACTIONS t
JOIN CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
WHERE t.COUNTERPARTY_COUNTRY IN ('Russia','Belarus','Belize','Panama','Cayman Islands',
    'British Virgin Islands','Iran','North Korea','Myanmar','Cyprus','Malta','Latvia')
   OR c.JURISDICTION_RISK = 'HIGH';

-- Dormant account reactivation
CREATE OR REPLACE VIEW V_DORMANT_REACTIVATION AS
WITH last_old_activity AS (
    SELECT CUSTOMER_ID, MAX(TXN_DATE) AS LAST_ACTIVITY_BEFORE
    FROM TRANSACTIONS WHERE TXN_DATE < DATEADD('day', -90, CURRENT_TIMESTAMP())
    GROUP BY CUSTOMER_ID
),
recent_activity AS (
    SELECT CUSTOMER_ID, MIN(TXN_DATE) AS REACTIVATION_DATE,
        COUNT(*) AS RECENT_TXN_COUNT, SUM(AMOUNT) AS RECENT_TOTAL_AMOUNT
    FROM TRANSACTIONS WHERE TXN_DATE >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY CUSTOMER_ID
)
SELECT r.CUSTOMER_ID, c.FULL_NAME, l.LAST_ACTIVITY_BEFORE, r.REACTIVATION_DATE,
    DATEDIFF('day', l.LAST_ACTIVITY_BEFORE, r.REACTIVATION_DATE) AS DORMANCY_DAYS,
    r.RECENT_TXN_COUNT, r.RECENT_TOTAL_AMOUNT
FROM recent_activity r
JOIN last_old_activity l ON r.CUSTOMER_ID = l.CUSTOMER_ID
JOIN CUSTOMERS c ON r.CUSTOMER_ID = c.CUSTOMER_ID
WHERE DATEDIFF('day', l.LAST_ACTIVITY_BEFORE, r.REACTIVATION_DATE) >= 90;

-- Audit log for copilot interactions
CREATE OR REPLACE TABLE COPILOT_AUDIT_LOG (
    LOG_ID INT AUTOINCREMENT,
    ACTION_TYPE VARCHAR(50),
    ALERT_ID VARCHAR(20),
    USER_QUERY VARCHAR(2000),
    RAG_CONTEXT VARCHAR(8000),
    LLM_RESPONSE VARCHAR(16000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER()
);
