-- ============================================================
-- Risk, Fraud & Regulatory Intelligence Copilot
-- Step 6: Data Pipeline (Stream, Dynamic Table, Tasks)
-- ============================================================

USE SCHEMA RISK_COPILOT.PUBLIC;

-- CDC stream on transactions for incremental processing
CREATE OR REPLACE STREAM TRANSACTIONS_STREAM ON TABLE TRANSACTIONS APPEND_ONLY = TRUE;

-- Dynamic table: real-time customer risk summary (auto-refreshes)
CREATE OR REPLACE DYNAMIC TABLE DT_CUSTOMER_RISK_SUMMARY
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    c.CUSTOMER_ID, c.FULL_NAME, c.COUNTRY, c.RISK_TIER, c.KYC_STATUS, c.PEP_FLAG,
    COALESCE(rs.COMPOSITE_SCORE, 0) AS COMPOSITE_RISK_SCORE,
    COALESCE(rs.RISK_CATEGORY, 'UNKNOWN') AS RISK_CATEGORY,
    COUNT(t.TXN_ID) AS TOTAL_TRANSACTIONS,
    COALESCE(SUM(t.AMOUNT), 0) AS TOTAL_AMOUNT,
    COUNT(CASE WHEN t.TXN_TYPE = 'WIRE_TRANSFER' THEN 1 END) AS WIRE_COUNT,
    COUNT(CASE WHEN t.TXN_TYPE = 'CASH_DEPOSIT' THEN 1 END) AS CASH_DEPOSIT_COUNT,
    COUNT(DISTINCT t.COUNTERPARTY_COUNTRY) AS UNIQUE_COUNTRIES,
    MAX(t.TXN_DATE) AS LAST_TRANSACTION_DATE,
    COUNT(a.ALERT_ID) AS OPEN_ALERT_COUNT
FROM CUSTOMERS c
LEFT JOIN TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN RISK_SCORES rs ON c.CUSTOMER_ID = rs.CUSTOMER_ID
LEFT JOIN ALERTS a ON c.CUSTOMER_ID = a.CUSTOMER_ID AND a.STATUS != 'CLOSED'
GROUP BY c.CUSTOMER_ID, c.FULL_NAME, c.COUNTRY, c.RISK_TIER, c.KYC_STATUS, c.PEP_FLAG,
         rs.COMPOSITE_SCORE, rs.RISK_CATEGORY;

-- Automated alert detection: runs every 15 min when new transactions arrive
CREATE OR REPLACE TASK TASK_AUTO_ALERT_DETECTION
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON */15 * * * * UTC'
  COMMENT = 'Automated structuring detection every 15 minutes'
  WHEN SYSTEM$STREAM_HAS_DATA('RISK_COPILOT.PUBLIC.TRANSACTIONS_STREAM')
AS
INSERT INTO ALERTS (ALERT_ID, CUSTOMER_ID, ALERT_TYPE, SEVERITY, STATUS, CREATED_AT, ASSIGNED_TO, DESCRIPTION, RELATED_TXNS)
SELECT
    'ALT-AUTO-' || TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS') || '-' || CUSTOMER_ID,
    CUSTOMER_ID, 'STRUCTURING', 'HIGH', 'OPEN', CURRENT_TIMESTAMP(), 'auto_detection',
    'Automated detection: ' || COUNT(*) || ' cash deposits under $10,000 within 24 hours totaling $' || ROUND(SUM(AMOUNT), 2),
    LISTAGG(TXN_ID, ',') WITHIN GROUP (ORDER BY TXN_DATE)
FROM TRANSACTIONS_STREAM
WHERE TXN_TYPE = 'CASH_DEPOSIT' AND AMOUNT BETWEEN 8000 AND 9999
GROUP BY CUSTOMER_ID, DATE(TXN_DATE) HAVING COUNT(*) >= 2;

ALTER TASK TASK_AUTO_ALERT_DETECTION RESUME;

-- Daily risk score refresh at 6AM UTC
CREATE OR REPLACE TASK TASK_DAILY_RISK_REFRESH
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  COMMENT = 'Daily risk score recalculation at 6AM UTC'
AS
  MERGE INTO RISK_SCORES rs
  USING (
    SELECT c.CUSTOMER_ID, CURRENT_DATE() AS SCORE_DATE,
      LEAST(1.0, COALESCE((SELECT COUNT(DISTINCT COUNTERPARTY_COUNTRY) FROM TRANSACTIONS t 
         WHERE t.CUSTOMER_ID = c.CUSTOMER_ID AND t.TXN_DATE >= DATEADD('day', -30, CURRENT_TIMESTAMP())) * 0.1, 0)) AS BEHAVIORAL_RISK,
      CASE c.JURISDICTION_RISK WHEN 'HIGH' THEN 0.8 WHEN 'MEDIUM' THEN 0.4 ELSE 0.05 END AS JURISDICTIONAL_RISK,
      LEAST(1.0, COALESCE((SELECT COUNT(*) FROM ALERTS a 
         WHERE a.CUSTOMER_ID = c.CUSTOMER_ID AND a.STATUS != 'CLOSED') * 0.25, 0)) AS NETWORK_RISK,
      'v2.1' AS MODEL_VERSION
    FROM CUSTOMERS c
  ) AS calc ON rs.CUSTOMER_ID = calc.CUSTOMER_ID
  WHEN MATCHED THEN UPDATE SET
    rs.SCORE_DATE = calc.SCORE_DATE, rs.BEHAVIORAL_RISK = calc.BEHAVIORAL_RISK,
    rs.JURISDICTIONAL_RISK = calc.JURISDICTIONAL_RISK, rs.NETWORK_RISK = calc.NETWORK_RISK,
    rs.COMPOSITE_SCORE = ROUND((calc.BEHAVIORAL_RISK * 0.4 + calc.JURISDICTIONAL_RISK * 0.3 + calc.NETWORK_RISK * 0.3), 2),
    rs.RISK_CATEGORY = CASE 
      WHEN (calc.BEHAVIORAL_RISK*0.4 + calc.JURISDICTIONAL_RISK*0.3 + calc.NETWORK_RISK*0.3) >= 0.8 THEN 'CRITICAL'
      WHEN (calc.BEHAVIORAL_RISK*0.4 + calc.JURISDICTIONAL_RISK*0.3 + calc.NETWORK_RISK*0.3) >= 0.5 THEN 'HIGH'
      WHEN (calc.BEHAVIORAL_RISK*0.4 + calc.JURISDICTIONAL_RISK*0.3 + calc.NETWORK_RISK*0.3) >= 0.3 THEN 'MEDIUM'
      ELSE 'LOW' END,
    rs.MODEL_VERSION = calc.MODEL_VERSION;

ALTER TASK TASK_DAILY_RISK_REFRESH RESUME;
