-- ============================================================
-- Risk, Fraud & Regulatory Intelligence Copilot
-- Step 10: Transform Layer (Dynamic Tables)
-- ============================================================
-- All dynamic tables auto-refresh from RAW schema.
-- When new data lands in RAW, TRANSFORM updates automatically.

USE SCHEMA RISK_COPILOT.TRANSFORM;

-- ── DT_CUSTOMERS: Enriched customer profiles ──
CREATE OR REPLACE DYNAMIC TABLE DT_CUSTOMERS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    CUSTOMER_ID, FULL_NAME, EMAIL, PHONE, ADDRESS, COUNTRY,
    JURISDICTION_RISK, ACCOUNT_TYPE, KYC_STATUS, PEP_FLAG,
    ACCOUNT_OPEN_DATE, LAST_ACTIVITY_DATE, RISK_TIER, INGESTED_AT,
    DATEDIFF('day', ACCOUNT_OPEN_DATE, CURRENT_DATE()) AS ACCOUNT_AGE_DAYS,
    CASE WHEN DATEDIFF('day', LAST_ACTIVITY_DATE, CURRENT_DATE()) <= 90 THEN TRUE ELSE FALSE END AS IS_ACTIVE,
    DATEDIFF('day', LAST_ACTIVITY_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_ACTIVITY,
    CASE
        WHEN KYC_STATUS = 'EXPIRED' THEN 'RENEWAL_REQUIRED'
        WHEN KYC_STATUS = 'PENDING' THEN 'REVIEW_REQUIRED'
        ELSE 'CURRENT'
    END AS KYC_ACTION_NEEDED
FROM RISK_COPILOT.RAW.RAW_CUSTOMERS;


-- ── DT_TRANSACTIONS: Enriched transactions with risk flags ──
CREATE OR REPLACE DYNAMIC TABLE DT_TRANSACTIONS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    TXN_ID, CUSTOMER_ID, TXN_DATE, TXN_TYPE, AMOUNT, CURRENCY,
    COUNTERPARTY, COUNTERPARTY_COUNTRY, CHANNEL, STATUS, DESCRIPTION, INGESTED_AT,
    TXN_DATE::DATE AS TXN_DAY,
    CASE
        WHEN AMOUNT < 1000 THEN 'MICRO'
        WHEN AMOUNT < 10000 THEN 'SMALL'
        WHEN AMOUNT < 100000 THEN 'MEDIUM'
        WHEN AMOUNT < 1000000 THEN 'LARGE'
        ELSE 'JUMBO'
    END AS AMOUNT_BUCKET,
    CASE WHEN AMOUNT >= 10000 THEN TRUE ELSE FALSE END AS IS_CTR_REPORTABLE,
    CASE WHEN AMOUNT >= 100000 THEN TRUE ELSE FALSE END AS IS_HIGH_VALUE,
    CASE WHEN COUNTERPARTY_COUNTRY IN ('Belize','Panama','Cayman Islands','Cyprus','Malta','Latvia','Bahamas') THEN TRUE ELSE FALSE END AS IS_HIGH_RISK_DESTINATION
FROM RISK_COPILOT.RAW.RAW_TRANSACTIONS;


-- ── DT_RISK_ENRICHED: Customer + risk scores combined ──
CREATE OR REPLACE DYNAMIC TABLE DT_RISK_ENRICHED
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    c.CUSTOMER_ID, c.FULL_NAME, c.COUNTRY, c.ACCOUNT_TYPE, c.KYC_STATUS,
    c.PEP_FLAG, c.RISK_TIER, c.IS_ACTIVE, c.KYC_ACTION_NEEDED,
    COALESCE(rs.BEHAVIORAL_RISK, 0) AS BEHAVIORAL_RISK,
    COALESCE(rs.JURISDICTIONAL_RISK, 0) AS JURISDICTIONAL_RISK,
    COALESCE(rs.NETWORK_RISK, 0) AS NETWORK_RISK,
    COALESCE(rs.COMPOSITE_SCORE, 0) AS COMPOSITE_SCORE,
    COALESCE(rs.RISK_CATEGORY, 'UNSCORED') AS RISK_CATEGORY,
    rs.MODEL_VERSION,
    rs.SCORE_DATE,
    CASE
        WHEN rs.COMPOSITE_SCORE >= 0.8 THEN 'IMMEDIATE_REVIEW'
        WHEN rs.COMPOSITE_SCORE >= 0.5 THEN 'ENHANCED_MONITORING'
        WHEN rs.COMPOSITE_SCORE >= 0.3 THEN 'STANDARD_MONITORING'
        ELSE 'LOW_TOUCH'
    END AS MONITORING_LEVEL
FROM RISK_COPILOT.TRANSFORM.DT_CUSTOMERS c
LEFT JOIN RISK_COPILOT.RAW.RAW_RISK_SCORES rs ON c.CUSTOMER_ID = rs.CUSTOMER_ID;


-- ── DT_ALERT_ENRICHED: Alerts with customer context ──
CREATE OR REPLACE DYNAMIC TABLE DT_ALERT_ENRICHED
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    a.ALERT_ID, a.CUSTOMER_ID, a.ALERT_TYPE, a.SEVERITY, a.STATUS,
    a.CREATED_AT, a.ASSIGNED_TO, a.DESCRIPTION, a.RELATED_TXNS,
    c.FULL_NAME AS CUSTOMER_NAME, c.COUNTRY AS CUSTOMER_COUNTRY,
    c.PEP_FLAG, c.KYC_STATUS, c.RISK_TIER,
    DATEDIFF('day', a.CREATED_AT, CURRENT_TIMESTAMP()) AS ALERT_AGE_DAYS,
    CASE
        WHEN a.SEVERITY = 'CRITICAL' AND DATEDIFF('hour', a.CREATED_AT, CURRENT_TIMESTAMP()) > 24 THEN 'SLA_BREACHED'
        WHEN a.SEVERITY = 'HIGH' AND DATEDIFF('hour', a.CREATED_AT, CURRENT_TIMESTAMP()) > 72 THEN 'SLA_BREACHED'
        WHEN a.SEVERITY = 'CRITICAL' AND DATEDIFF('hour', a.CREATED_AT, CURRENT_TIMESTAMP()) > 12 THEN 'SLA_WARNING'
        WHEN a.SEVERITY = 'HIGH' AND DATEDIFF('hour', a.CREATED_AT, CURRENT_TIMESTAMP()) > 48 THEN 'SLA_WARNING'
        ELSE 'WITHIN_SLA'
    END AS SLA_STATUS
FROM RISK_COPILOT.RAW.RAW_ALERTS a
LEFT JOIN RISK_COPILOT.TRANSFORM.DT_CUSTOMERS c ON a.CUSTOMER_ID = c.CUSTOMER_ID;


-- ── DT_CUSTOMER_RISK_SUMMARY: Aggregated risk profile per customer ──
CREATE OR REPLACE DYNAMIC TABLE DT_CUSTOMER_RISK_SUMMARY
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
SELECT
    c.CUSTOMER_ID, c.FULL_NAME, c.COUNTRY, c.RISK_TIER, c.KYC_STATUS, c.PEP_FLAG,
    COALESCE(rs.COMPOSITE_SCORE, 0) AS COMPOSITE_RISK_SCORE,
    COALESCE(rs.RISK_CATEGORY, 'UNKNOWN') AS RISK_CATEGORY,
    COUNT(t.TXN_ID) AS TOTAL_TRANSACTIONS,
    COALESCE(SUM(t.AMOUNT), 0) AS TOTAL_AMOUNT,
    COUNT(CASE WHEN t.TXN_TYPE = 'WIRE_TRANSFER' THEN 1 END) AS WIRE_COUNT,
    COUNT(CASE WHEN t.TXN_TYPE = 'CASH_DEPOSIT' THEN 1 END) AS CASH_DEPOSIT_COUNT,
    COUNT(CASE WHEN t.IS_HIGH_VALUE THEN 1 END) AS HIGH_VALUE_TXN_COUNT,
    COUNT(CASE WHEN t.IS_HIGH_RISK_DESTINATION THEN 1 END) AS HIGH_RISK_DEST_COUNT,
    COUNT(DISTINCT t.COUNTERPARTY_COUNTRY) AS UNIQUE_COUNTRIES,
    MAX(t.TXN_DATE) AS LAST_TRANSACTION_DATE,
    COUNT(a.ALERT_ID) AS OPEN_ALERT_COUNT
FROM RISK_COPILOT.TRANSFORM.DT_CUSTOMERS c
LEFT JOIN RISK_COPILOT.TRANSFORM.DT_TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
LEFT JOIN RISK_COPILOT.RAW.RAW_RISK_SCORES rs ON c.CUSTOMER_ID = rs.CUSTOMER_ID
LEFT JOIN RISK_COPILOT.RAW.RAW_ALERTS a ON c.CUSTOMER_ID = a.CUSTOMER_ID AND a.STATUS != 'CLOSED'
GROUP BY c.CUSTOMER_ID, c.FULL_NAME, c.COUNTRY, c.RISK_TIER, c.KYC_STATUS, c.PEP_FLAG,
         rs.COMPOSITE_SCORE, rs.RISK_CATEGORY;


-- ── DT_SUSPICIOUS_PATTERNS: Consolidated detection across all 4 pattern types ──
CREATE OR REPLACE DYNAMIC TABLE DT_SUSPICIOUS_PATTERNS
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
AS
-- Structuring: multiple cash deposits under $10k in one day
SELECT
    'STRUCTURING' AS PATTERN_TYPE,
    t.CUSTOMER_ID,
    c.FULL_NAME,
    t.TXN_DAY AS DETECTION_DATE,
    COUNT(*) AS EVENT_COUNT,
    SUM(t.AMOUNT) AS TOTAL_AMOUNT,
    'Multiple cash deposits under $10k CTR threshold in single day' AS PATTERN_DESCRIPTION
FROM RISK_COPILOT.TRANSFORM.DT_TRANSACTIONS t
JOIN RISK_COPILOT.TRANSFORM.DT_CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
WHERE t.TXN_TYPE = 'CASH_DEPOSIT' AND t.AMOUNT BETWEEN 8000 AND 9999
GROUP BY t.CUSTOMER_ID, c.FULL_NAME, t.TXN_DAY
HAVING COUNT(*) >= 2

UNION ALL

-- Velocity anomaly: 5+ transfers to different countries in one day
SELECT
    'VELOCITY_ANOMALY' AS PATTERN_TYPE,
    t.CUSTOMER_ID,
    c.FULL_NAME,
    t.TXN_DAY AS DETECTION_DATE,
    COUNT(*) AS EVENT_COUNT,
    SUM(t.AMOUNT) AS TOTAL_AMOUNT,
    'High velocity transfers to multiple countries in single day' AS PATTERN_DESCRIPTION
FROM RISK_COPILOT.TRANSFORM.DT_TRANSACTIONS t
JOIN RISK_COPILOT.TRANSFORM.DT_CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
WHERE t.TXN_TYPE = 'WIRE_TRANSFER'
GROUP BY t.CUSTOMER_ID, c.FULL_NAME, t.TXN_DAY
HAVING COUNT(DISTINCT t.COUNTERPARTY_COUNTRY) >= 3

UNION ALL

-- High-risk destination transfers
SELECT
    'HIGH_RISK_DESTINATION' AS PATTERN_TYPE,
    t.CUSTOMER_ID,
    c.FULL_NAME,
    t.TXN_DAY AS DETECTION_DATE,
    COUNT(*) AS EVENT_COUNT,
    SUM(t.AMOUNT) AS TOTAL_AMOUNT,
    'Wire transfers to high-risk jurisdictions' AS PATTERN_DESCRIPTION
FROM RISK_COPILOT.TRANSFORM.DT_TRANSACTIONS t
JOIN RISK_COPILOT.TRANSFORM.DT_CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
WHERE t.IS_HIGH_RISK_DESTINATION = TRUE AND t.TXN_TYPE = 'WIRE_TRANSFER'
GROUP BY t.CUSTOMER_ID, c.FULL_NAME, t.TXN_DAY

UNION ALL

-- Dormant reactivation: no activity for 180+ days then sudden large transactions
SELECT
    'DORMANT_REACTIVATION' AS PATTERN_TYPE,
    c.CUSTOMER_ID,
    c.FULL_NAME,
    CURRENT_DATE() AS DETECTION_DATE,
    COUNT(t.TXN_ID) AS EVENT_COUNT,
    COALESCE(SUM(t.AMOUNT), 0) AS TOTAL_AMOUNT,
    'Account dormant 180+ days with recent large transactions' AS PATTERN_DESCRIPTION
FROM RISK_COPILOT.TRANSFORM.DT_CUSTOMERS c
JOIN RISK_COPILOT.TRANSFORM.DT_TRANSACTIONS t ON c.CUSTOMER_ID = t.CUSTOMER_ID
WHERE c.DAYS_SINCE_LAST_ACTIVITY > 180
  AND t.TXN_DATE >= DATEADD('day', -30, CURRENT_TIMESTAMP())
  AND t.AMOUNT >= 10000
GROUP BY c.CUSTOMER_ID, c.FULL_NAME;
