-- ============================================================
-- Risk, Fraud & Regulatory Intelligence Copilot
-- Step 11: Daily Data Ingestion Task
-- ============================================================
-- Simulates daily transaction feed by generating synthetic
-- transactions for random customers each day.
-- Dynamic tables in TRANSFORM auto-refresh when new RAW data lands.

USE SCHEMA RISK_COPILOT.RAW;

-- Daily ingestion: generates 5-10 new synthetic transactions per run
CREATE OR REPLACE TASK RISK_COPILOT.RAW.TASK_DAILY_DATA_INGESTION
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
  COMMENT = 'Daily synthetic transaction ingestion at 2AM UTC - simulates real-time data feed'
AS
INSERT INTO RISK_COPILOT.RAW.RAW_TRANSACTIONS (TXN_ID, CUSTOMER_ID, TXN_DATE, TXN_TYPE, AMOUNT, CURRENCY, COUNTERPARTY, COUNTERPARTY_COUNTRY, CHANNEL, STATUS, DESCRIPTION)
SELECT
    'TXN-AUTO-' || TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD') || '-' || SEQ4() AS TXN_ID,
    cust.CUSTOMER_ID,
    DATEADD('hour', -1 * UNIFORM(1, 23, RANDOM()), CURRENT_TIMESTAMP()) AS TXN_DATE,
    txn_types.TXN_TYPE,
    ROUND(UNIFORM(100, 500000, RANDOM())::FLOAT * 
        CASE WHEN cust.RISK_TIER = 'HIGH' THEN 2.0 WHEN cust.RISK_TIER = 'MEDIUM' THEN 1.0 ELSE 0.3 END, 2) AS AMOUNT,
    CASE WHEN UNIFORM(1, 10, RANDOM()) <= 7 THEN 'USD' 
         WHEN UNIFORM(1, 10, RANDOM()) <= 9 THEN 'EUR' ELSE 'GBP' END AS CURRENCY,
    CASE txn_types.TXN_TYPE
        WHEN 'WIRE_TRANSFER' THEN countries.COUNTERPARTY
        WHEN 'CASH_DEPOSIT' THEN 'Self'
        WHEN 'ACH_TRANSFER' THEN 'Domestic Entity'
        ELSE 'Merchant'
    END AS COUNTERPARTY,
    CASE txn_types.TXN_TYPE
        WHEN 'WIRE_TRANSFER' THEN countries.COUNTRY_NAME
        WHEN 'CASH_DEPOSIT' THEN cust.COUNTRY
        ELSE cust.COUNTRY
    END AS COUNTERPARTY_COUNTRY,
    CASE WHEN txn_types.TXN_TYPE IN ('WIRE_TRANSFER','ACH_TRANSFER') THEN 'ONLINE'
         WHEN txn_types.TXN_TYPE = 'CASH_DEPOSIT' THEN 'BRANCH'
         ELSE 'POS' END AS CHANNEL,
    'COMPLETED' AS STATUS,
    'Auto-generated daily transaction - ' || txn_types.TXN_TYPE AS DESCRIPTION
FROM (SELECT CUSTOMER_ID, COUNTRY, RISK_TIER FROM RISK_COPILOT.RAW.RAW_CUSTOMERS ORDER BY RANDOM() LIMIT 8) cust
CROSS JOIN (
    SELECT column1 AS TXN_TYPE FROM VALUES ('WIRE_TRANSFER'),('CASH_DEPOSIT'),('ACH_TRANSFER'),('DEBIT_CARD')
    ORDER BY RANDOM() LIMIT 1
) txn_types
CROSS JOIN (
    SELECT column1 AS COUNTERPARTY, column2 AS COUNTRY_NAME FROM VALUES
    ('Global Trading Corp','United Kingdom'),('Pacific Holdings','Singapore'),
    ('Euro Finance SA','Switzerland'),('Caribbean Trust','Cayman Islands'),
    ('Nordic Capital AB','Sweden'),('Istanbul Imports','Turkey'),
    ('Malta Investments','Malta'),('Berlin GmbH','Germany')
    ORDER BY RANDOM() LIMIT 1
) countries;

ALTER TASK RISK_COPILOT.RAW.TASK_DAILY_DATA_INGESTION RESUME;

-- Also update the existing alert detection task to read from TRANSFORM
USE SCHEMA RISK_COPILOT.PUBLIC;

-- Stream on RAW transactions for CDC
CREATE OR REPLACE STREAM RISK_COPILOT.RAW.RAW_TRANSACTIONS_STREAM 
  ON TABLE RISK_COPILOT.RAW.RAW_TRANSACTIONS APPEND_ONLY = TRUE;

-- Alert detection reads from stream, writes to RAW_ALERTS
CREATE OR REPLACE TASK RISK_COPILOT.RAW.TASK_AUTO_ALERT_DETECTION
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON */15 * * * * UTC'
  COMMENT = 'Automated structuring detection every 15 minutes from RAW stream'
  WHEN SYSTEM$STREAM_HAS_DATA('RISK_COPILOT.RAW.RAW_TRANSACTIONS_STREAM')
AS
INSERT INTO RISK_COPILOT.RAW.RAW_ALERTS (ALERT_ID, CUSTOMER_ID, ALERT_TYPE, SEVERITY, STATUS, CREATED_AT, ASSIGNED_TO, DESCRIPTION, RELATED_TXNS)
SELECT
    'ALT-AUTO-' || TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS') || '-' || CUSTOMER_ID,
    CUSTOMER_ID, 'STRUCTURING', 'HIGH', 'OPEN', CURRENT_TIMESTAMP(), 'auto_detection',
    'Automated detection: ' || COUNT(*) || ' cash deposits under $10,000 within 24 hours totaling $' || ROUND(SUM(AMOUNT), 2),
    LISTAGG(TXN_ID, ',') WITHIN GROUP (ORDER BY TXN_DATE)
FROM RISK_COPILOT.RAW.RAW_TRANSACTIONS_STREAM
WHERE TXN_TYPE = 'CASH_DEPOSIT' AND AMOUNT BETWEEN 8000 AND 9999
GROUP BY CUSTOMER_ID, DATE(TXN_DATE) HAVING COUNT(*) >= 2;

ALTER TASK RISK_COPILOT.RAW.TASK_AUTO_ALERT_DETECTION RESUME;

-- Daily risk score refresh
CREATE OR REPLACE TASK RISK_COPILOT.RAW.TASK_DAILY_RISK_REFRESH
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  COMMENT = 'Daily risk score recalculation at 6AM UTC'
AS
  MERGE INTO RISK_COPILOT.RAW.RAW_RISK_SCORES rs
  USING (
    SELECT c.CUSTOMER_ID, CURRENT_DATE() AS SCORE_DATE,
      LEAST(1.0, COALESCE((SELECT COUNT(DISTINCT COUNTERPARTY_COUNTRY) FROM RISK_COPILOT.RAW.RAW_TRANSACTIONS t 
         WHERE t.CUSTOMER_ID = c.CUSTOMER_ID AND t.TXN_DATE >= DATEADD('day', -30, CURRENT_TIMESTAMP())) * 0.1, 0)) AS BEHAVIORAL_RISK,
      CASE c.JURISDICTION_RISK WHEN 'HIGH' THEN 0.8 WHEN 'MEDIUM' THEN 0.4 ELSE 0.05 END AS JURISDICTIONAL_RISK,
      LEAST(1.0, COALESCE((SELECT COUNT(*) FROM RISK_COPILOT.RAW.RAW_ALERTS a 
         WHERE a.CUSTOMER_ID = c.CUSTOMER_ID AND a.STATUS != 'CLOSED') * 0.25, 0)) AS NETWORK_RISK,
      'v2.1' AS MODEL_VERSION
    FROM RISK_COPILOT.RAW.RAW_CUSTOMERS c
  ) AS calc ON rs.CUSTOMER_ID = calc.CUSTOMER_ID
  WHEN MATCHED THEN UPDATE SET
    rs.SCORE_DATE = calc.SCORE_DATE, rs.BEHAVIORAL_RISK = calc.BEHAVIORAL_RISK,
    rs.JURISDICTIONAL_RISK = calc.JURISDICTIONAL_RISK, rs.NETWORK_RISK = calc.NETWORK_RISK,
    rs.COMPOSITE_SCORE = ROUND((calc.BEHAVIORAL_RISK * 0.4 + calc.JURISDICTIONAL_RISK * 0.3 + calc.NETWORK_RISK * 0.3), 2),
    rs.RISK_CATEGORY = CASE 
      WHEN (calc.BEHAVIORAL_RISK*0.4 + calc.JURISDICTIONAL_RISK*0.3 + calc.NETWORK_RISK*0.3) >= 0.8 THEN 'CRITICAL'
      WHEN (calc.BEHAVIORAL_RISK*0.4 + calc.JURISDICTIONAL_RISK*0.3 + calc.NETWORK_RISK*0.3) >= 0.5 THEN 'HIGH'
      WHEN (calc.BEHAVIORAL_RISK*0.4 + calc.JURISDICTIONAL_RISK*0.3 + calc.NETWORK_RISK*0.3) >= 0.3 THEN 'MEDIUM'
      ELSE 'LOW' END,
    rs.MODEL_VERSION = calc.MODEL_VERSION;

ALTER TASK RISK_COPILOT.RAW.TASK_DAILY_RISK_REFRESH RESUME;
