-- ============================================================
-- Risk, Fraud & Regulatory Intelligence Copilot
-- Step 6: Governance - RBAC, Tagging, Masking Policies
-- ============================================================

USE SCHEMA RISK_COPILOT.PUBLIC;

-- PII tagging
ALTER TABLE CUSTOMERS MODIFY COLUMN FULL_NAME SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'NAME';
ALTER TABLE CUSTOMERS MODIFY COLUMN EMAIL SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'EMAIL';
ALTER TABLE CUSTOMERS MODIFY COLUMN PHONE SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'PHONE_NUMBER';
ALTER TABLE CUSTOMERS MODIFY COLUMN ADDRESS SET TAG SNOWFLAKE.CORE.SEMANTIC_CATEGORY = 'US_STREET_ADDRESS';

-- Roles
CREATE ROLE IF NOT EXISTS RISK_ANALYST COMMENT = 'Can investigate alerts, run copilot, generate evidence';
CREATE ROLE IF NOT EXISTS RISK_AUDITOR COMMENT = 'Read-only access to all data and audit trail';
GRANT ROLE RISK_ANALYST TO ROLE ACCOUNTADMIN;
GRANT ROLE RISK_AUDITOR TO ROLE ACCOUNTADMIN;

-- Database + schema + warehouse access
GRANT USAGE ON DATABASE RISK_COPILOT TO ROLE RISK_ANALYST;
GRANT USAGE ON DATABASE RISK_COPILOT TO ROLE RISK_AUDITOR;
GRANT USAGE ON SCHEMA RISK_COPILOT.PUBLIC TO ROLE RISK_ANALYST;
GRANT USAGE ON SCHEMA RISK_COPILOT.PUBLIC TO ROLE RISK_AUDITOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE RISK_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE RISK_AUDITOR;

-- RISK_ANALYST permissions
GRANT SELECT ON ALL TABLES IN SCHEMA RISK_COPILOT.PUBLIC TO ROLE RISK_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA RISK_COPILOT.PUBLIC TO ROLE RISK_ANALYST;
GRANT INSERT ON TABLE COPILOT_AUDIT_LOG TO ROLE RISK_ANALYST;
GRANT UPDATE ON TABLE ALERTS TO ROLE RISK_ANALYST;
GRANT USAGE ON STREAMLIT RISK_FRAUD_COPILOT TO ROLE RISK_ANALYST;

-- RISK_AUDITOR permissions (read-only)
GRANT SELECT ON ALL TABLES IN SCHEMA RISK_COPILOT.PUBLIC TO ROLE RISK_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA RISK_COPILOT.PUBLIC TO ROLE RISK_AUDITOR;
GRANT USAGE ON STREAMLIT RISK_FRAUD_COPILOT TO ROLE RISK_AUDITOR;

-- Masking policy for PII
CREATE OR REPLACE MASKING POLICY PII_MASK AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'RISK_ANALYST') THEN val
        ELSE '***MASKED***'
    END;

ALTER TABLE CUSTOMERS MODIFY COLUMN FULL_NAME SET MASKING POLICY PII_MASK;
ALTER TABLE CUSTOMERS MODIFY COLUMN EMAIL SET MASKING POLICY PII_MASK;
ALTER TABLE CUSTOMERS MODIFY COLUMN PHONE SET MASKING POLICY PII_MASK;
ALTER TABLE CUSTOMERS MODIFY COLUMN ADDRESS SET MASKING POLICY PII_MASK;
